### PR TITLE
Support Get/Set of Farenheit

### PR DESCRIPTION
**Pull request by cmroche**
Properly support get/set of Farenheit temperature.

Fixes: https://github.com/home-assistant/core/issues/49768

### CODE REVIEW

**Comment by seantibor** [comment]
Here's the error I'm getting. I think that the most recent updates you made for upcoming Home Assistant changes to config flow is not compatible with my 2021.4.6 version. I tried it with the latest 2021.5.0b8 beta release and got the same result.

```2021-05-05 12:43:29 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration gree - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 98, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 281, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 493, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/_gree/config_flow.py", line 16, in <module>
    config_entry_flow.register_discovery_flow(DOMAIN, "Gree Climate", _async_has_devices)
TypeError: register_discovery_flow() missing 1 required positional argument: 'connection_class'
```

**Comment by cmroche** [comment]
@seantibor The reason for this is because the test branch is developed to work off the "dev" branch on HomeAssistant. If you open config_flow.py though, look for this line:

```python
config_entry_flow.register_discovery_flow(DOMAIN, "Gree Climate", _async_has_devices)
```

and replace it with this line:

```python
config_entry_flow.register_discovery_flow(
    DOMAIN, "Gree Climate", _async_has_devices, config_entries.CONN_CLASS_LOCAL_POLL
)
```

That will work around the issue until the next official release of HA.

**Comment by seantibor** [comment]
OK -- since I'm running docker, I just tried running the dev image and it seems to be loading ok now. The temperature shows up in the same temperature units, but now I am getting some strange behavior when changing the temperature setting.

It seems to be ok lowering the temp by a degree, but when I try to raise it by a degree I get the error below in the logs. [Here's a screencast ](https://www.loom.com/share/d940479a186d4707be23245cce749416)of what I'm doing in the UI. 

```2021-05-05 15:08:03 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140127634865504] Specified temperature is out of range.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 167, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 548, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/gree/climate.py", line 180, in async_set_temperature
    self.coordinator.device.target_temperature = round(temperature)
  File "/usr/local/lib/python3.8/site-packages/greeclimate/device.py", line 335, in target_temperature
    validate(rec["temSet"])
  File "/usr/local/lib/python3.8/site-packages/greeclimate/device.py", line 331, in validate
    raise ValueError("Specified temperature is out of range.")
ValueError: Specified temperature is out of range.```

**Comment by cmroche** [comment]
I hear the beep on the first one, so it must have gone through 😄 

Can you share the debug logs again, turn everything onto debug so what you did in the screencast, this should give me what I need to sort out the problem and make a fix.

Thanks.

**Comment by seantibor** [comment]
Here's the excerpt of a few attempts with debug turned on for greeclimate and gree component.

```
2021-05-05 19:10:45 DEBUG (MainThread) [greeclimate.device] Updating device properties for (Device: c62cc6ea @ 192.168.1.122:7000 (mac: 502cc62cc6ea))
2021-05-05 19:10:45 DEBUG (MainThread) [greeclimate.network] Sending packet:
{"cid": "app", "i": 0, "t": "pack", "uid": 0, "tcid": "502cc62cc6ea", "pack": {"mac": "502cc62cc6ea", "t": "status", "cols": ["Pow", "Mod", "SetTem", "TemSen", "TemUn", "TemRec", "WdSpd", "Air", "Blo", "Health", "SwhSlp", "SlpMod", "Lig", "SwingLfRig", "SwUpDn", "Quiet", "Tur", "StHt", "SvSt", "HeatCoolType"]}}
2021-05-05 19:10:45 DEBUG (MainThread) [greeclimate.network] Received packet:
{"t": "pack", "i": 0, "uid": 0, "cid": "502cc62cc6ea", "tcid": "", "pack": {"t": "dat", "mac": "502cc62cc6ea", "r": 200, "cols": ["Pow", "Mod", "SetTem", "TemSen", "TemUn", "TemRec", "WdSpd", "Air", "Blo", "Health", "SwhSlp", "SlpMod", "Lig", "SwingLfRig", "SwUpDn", "Quiet", "Tur", "StHt", "SvSt", "HeatCoolType"], "dat": [1, 1, 24, 65, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0]}}
2021-05-05 19:10:50 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.olga_the_robot_vacuum is taking over 10 seconds
2021-05-05 19:11:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.olga_the_robot_vacuum is taking over 10 seconds
2021-05-05 19:11:30 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.olga_the_robot_vacuum is taking over 10 seconds
2021-05-05 19:11:45 DEBUG (MainThread) [greeclimate.device] Updating device properties for (Device: c62cc6ea @ 192.168.1.122:7000 (mac: 502cc62cc6ea))
2021-05-05 19:11:45 DEBUG (MainThread) [greeclimate.network] Sending packet:
{"cid": "app", "i": 0, "t": "pack", "uid": 0, "tcid": "502cc62cc6ea", "pack": {"mac": "502cc62cc6ea", "t": "status", "cols": ["Pow", "Mod", "SetTem", "TemSen", "TemUn", "TemRec", "WdSpd", "Air", "Blo", "Health", "SwhSlp", "SlpMod", "Lig", "SwingLfRig", "SwUpDn", "Quiet", "Tur", "StHt", "SvSt", "HeatCoolType"]}}
2021-05-05 19:11:45 DEBUG (MainThread) [greeclimate.network] Received packet:
{"t": "pack", "i": 0, "uid": 0, "cid": "502cc62cc6ea", "tcid": "", "pack": {"t": "dat", "mac": "502cc62cc6ea", "r": 200, "cols": ["Pow", "Mod", "SetTem", "TemSen", "TemUn", "TemRec", "WdSpd", "Air", "Blo", "Health", "SwhSlp", "SlpMod", "Lig", "SwingLfRig", "SwUpDn", "Quiet", "Tur", "StHt", "SvSt", "HeatCoolType"], "dat": [1, 1, 24, 65, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0]}}
2021-05-05 19:11:50 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.olga_the_robot_vacuum is taking over 10 seconds
2021-05-05 19:12:07 INFO (MainThread) [homeassistant.components.automation.lock_garage_house_door] Lock Garage House Door: Test condition device: True
2021-05-05 19:12:07 INFO (MainThread) [homeassistant.components.automation.lock_garage_house_door] Lock Garage House Door: Choose at step 3: default: Running automation actions
2021-05-05 19:12:07 INFO (MainThread) [homeassistant.components.automation.lock_garage_house_door] Lock Garage House Door: Choose at step 3: default: Executing step device automation
2021-05-05 19:12:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.olga_the_robot_vacuum is taking over 10 seconds
2021-05-05 19:12:14 INFO (MainThread) [homeassistant.components.automation.turn_on_kids_doors_locked] Turn on Kids Doors Locked: Running automation actions
2021-05-05 19:12:14 INFO (MainThread) [homeassistant.components.automation.turn_on_kids_doors_locked] Turn on Kids Doors Locked: Executing step activate scene
2021-05-05 19:12:14 WARNING (MainThread) [homeassistant.components.switch.reproduce_state] Unable to find entity switch.kadens_lights
2021-05-05 19:12:15 INFO (MainThread) [homeassistant.components.automation.turn_on_kids_doors_locked] Turn on Kids Doors Locked: Test condition state: True
2021-05-05 19:12:15 INFO (MainThread) [homeassistant.components.automation.turn_on_kids_doors_locked] Turn on Kids Doors Locked: Executing step activate scene
2021-05-05 19:12:15 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.farrahs_bulb
2021-05-05 19:12:30 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.olga_the_robot_vacuum is taking over 10 seconds
2021-05-05 19:12:45 DEBUG (MainThread) [greeclimate.device] Updating device properties for (Device: c62cc6ea @ 192.168.1.122:7000 (mac: 502cc62cc6ea))
2021-05-05 19:12:45 DEBUG (MainThread) [greeclimate.network] Sending packet:
{"cid": "app", "i": 0, "t": "pack", "uid": 0, "tcid": "502cc62cc6ea", "pack": {"mac": "502cc62cc6ea", "t": "status", "cols": ["Pow", "Mod", "SetTem", "TemSen", "TemUn", "TemRec", "WdSpd", "Air", "Blo", "Health", "SwhSlp", "SlpMod", "Lig", "SwingLfRig", "SwUpDn", "Quiet", "Tur", "StHt", "SvSt", "HeatCoolType"]}}
2021-05-05 19:12:45 DEBUG (MainThread) [greeclimate.network] Received packet:
{"t": "pack", "i": 0, "uid": 0, "cid": "502cc62cc6ea", "tcid": "", "pack": {"t": "dat", "mac": "502cc62cc6ea", "r": 200, "cols": ["Pow", "Mod", "SetTem", "TemSen", "TemUn", "TemRec", "WdSpd", "Air", "Blo", "Health", "SwhSlp", "SlpMod", "Lig", "SwingLfRig", "SwUpDn", "Quiet", "Tur", "StHt", "SvSt", "HeatCoolType"], "dat": [1, 1, 24, 65, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0]}}
2021-05-05 19:12:50 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.olga_the_robot_vacuum is taking over 10 seconds
2021-05-05 19:13:05 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [140127756505536] Connection closed by client
2021-05-05 19:13:06 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140127972492912] Specified temperature is out of range.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 167, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 548, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/gree/climate.py", line 180, in async_set_temperature
    self.coordinator.device.target_temperature = round(temperature)
  File "/usr/local/lib/python3.8/site-packages/greeclimate/device.py", line 335, in target_temperature
    validate(rec["temSet"])
  File "/usr/local/lib/python3.8/site-packages/greeclimate/device.py", line 331, in validate
    raise ValueError("Specified temperature is out of range.")
ValueError: Specified temperature is out of range.
2021-05-05 19:13:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.olga_the_robot_vacuum is taking over 10 seconds
2021-05-05 19:13:11 INFO (MainThread) [homeassistant.components.automation.lock_garage_house_door] Lock Garage House Door: Restarting
2021-05-05 19:13:11 INFO (MainThread) [homeassistant.components.automation.lock_garage_house_door] Lock Garage House Door: Running automation actions
2021-05-05 19:13:11 INFO (MainThread) [homeassistant.components.automation.lock_garage_house_door] Lock Garage House Door: Executing step delay 0:05:00
2021-05-05 19:13:12 INFO (MainThread) [homeassistant.components.automation.lock_garage_house_door] Lock Garage House Door: Restarting
2021-05-05 19:13:12 INFO (MainThread) [homeassistant.components.automation.lock_garage_house_door] Lock Garage House Door: Running automation actions
2021-05-05 19:13:12 INFO (MainThread) [homeassistant.components.automation.lock_garage_house_door] Lock Garage House Door: Executing step delay 0:05:00
2021-05-05 19:13:16 INFO (MainThread) [homeassistant.components.automation.lock_garage_house_door] Lock Garage House Door: Restarting
2021-05-05 19:13:16 INFO (MainThread) [homeassistant.components.automation.lock_garage_house_door] Lock Garage House Door: Running automation actions
2021-05-05 19:13:16 INFO (MainThread) [homeassistant.components.automation.lock_garage_house_door] Lock Garage House Door: Executing step delay 0:05:00
2021-05-05 19:13:23 DEBUG (MainThread) [greeclimate.device] Pushing state updates to (Device: c62cc6ea @ 192.168.1.122:7000 (mac: 502cc62cc6ea))
2021-05-05 19:13:23 DEBUG (MainThread) [greeclimate.device] Sending remote state update SetTem -> 23
2021-05-05 19:13:23 DEBUG (MainThread) [greeclimate.device] Sending remote state update TemRec -> 1
2021-05-05 19:13:23 DEBUG (MainThread) [greeclimate.network] Sending packet:
{"cid": "app", "i": 0, "t": "pack", "uid": 0, "tcid": "502cc62cc6ea", "pack": {"opt": ["SetTem", "TemRec", "TemUn"], "p": [23, 1, 1], "t": "cmd"}}
2021-05-05 19:13:23 DEBUG (MainThread) [greeclimate.network] Received packet:
{"t": "pack", "i": 0, "uid": 0, "cid": "502cc62cc6ea", "tcid": "", "pack": {"t": "res", "mac": "502cc62cc6ea", "r": 200, "opt": ["SetTem", "TemRec", "TemUn"], "p": [23, 1, 1], "val": [23, 1, 1]}}
2021-05-05 19:13:23 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140127972492912] coroutine raised StopIteration
Traceback (most recent call last):
  File "/config/custom_components/gree/climate.py", line 182, in async_set_temperature
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 351, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 387, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 225, in state_attributes
    self.current_temperature,
  File "/config/custom_components/gree/climate.py", line 161, in current_temperature
    return self.coordinator.device.current_temperature
  File "/usr/local/lib/python3.8/site-packages/greeclimate/device.py", line 359, in current_temperature
    return self._convert_to_units(prop - 40, bit)
  File "/usr/local/lib/python3.8/site-packages/greeclimate/device.py", line 318, in _convert_to_units
    f = next(t for t in TEMP_TABLE if t["temSet"] == value and t["temRec"] == bit)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 167, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 548, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
RuntimeError: coroutine raised StopIteration
2021-05-05 19:13:30 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.olga_the_robot_vacuum is taking over 10 seconds
2021-05-05 19:13:37 DEBUG (MainThread) [greeclimate.device] Pushing state updates to (Device: c62cc6ea @ 192.168.1.122:7000 (mac: 502cc62cc6ea))
2021-05-05 19:13:37 DEBUG (MainThread) [greeclimate.device] Sending remote state update TemRec -> 0
2021-05-05 19:13:37 DEBUG (MainThread) [greeclimate.network] Sending packet:
{"cid": "app", "i": 0, "t": "pack", "uid": 0, "tcid": "502cc62cc6ea", "pack": {"opt": ["TemRec"], "p": [0], "t": "cmd"}}
2021-05-05 19:13:37 DEBUG (MainThread) [greeclimate.network] Received packet:
{"t": "pack", "i": 0, "uid": 0, "cid": "502cc62cc6ea", "tcid": "", "pack": {"t": "res", "mac": "502cc62cc6ea", "r": 200, "opt": ["TemRec"], "p": [0], "val": [0]}}
2021-05-05 19:13:45 DEBUG (MainThread) [greeclimate.device] Updating device properties for (Device: c62cc6ea @ 192.168.1.122:7000 (mac: 502cc62cc6ea))
2021-05-05 19:13:45 DEBUG (MainThread) [greeclimate.network] Sending packet:
{"cid": "app", "i": 0, "t": "pack", "uid": 0, "tcid": "502cc62cc6ea", "pack": {"mac": "502cc62cc6ea", "t": "status", "cols": ["Pow", "Mod", "SetTem", "TemSen", "TemUn", "TemRec", "WdSpd", "Air", "Blo", "Health", "SwhSlp", "SlpMod", "Lig", "SwingLfRig", "SwUpDn", "Quiet", "Tur", "StHt", "SvSt", "HeatCoolType"]}}
2021-05-05 19:13:45 DEBUG (MainThread) [greeclimate.network] Received packet:
{"t": "pack", "i": 0, "uid": 0, "cid": "502cc62cc6ea", "tcid": "", "pack": {"t": "dat", "mac": "502cc62cc6ea", "r": 200, "cols": ["Pow", "Mod", "SetTem", "TemSen", "TemUn", "TemRec", "WdSpd", "Air", "Blo", "Health", "SwhSlp", "SlpMod", "Lig", "SwingLfRig", "SwUpDn", "Quiet", "Tur", "StHt", "SvSt", "HeatCoolType"], "dat": [1, 1, 23, 65, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0]}}
```

**Pull request merged**
