### PR TITLE
Adds support for current temperature in newer firmware (TemSen)

### PR DESCRIPTION
**Pull request by xuefer**
works for me with all my up to date gree AC

### CODE REVIEW

**Comment by cmroche** [comment]
Thanks for the contribution @xuefer 

IIRC, there is a 40C offset that need to be subtracted from this, additionally I think we have to be careful about compatibility with older devices. In my past test, if you request for status updates from devices referencing a property that was unsupported, the device wouldn't respond. That may or not may apply for this field, and will need to be tested (and handled in case it is not.)

Once the behviour is known I'll add support into my device emulators and it will require proper unit tests for those conditions.

As for the firmware version in the response, the versions the discovery respond with doesn't map well to what is seen in the Gree+ app, it's not clear to me how these two are connected, but if required. Could you provide samples from the response data, and what is shown in Gree+ for some of your devices, maybe this will lead to clarity.

**Comment by xuefer** [comment]
Global Gree+
image

Chinese only Gree+ (actual name is 格力+)
image

```
2020-11-28 00:35:16 DEBUG (MainThread) [greeclimate.network] Received packet:
{"t": "pack", "i": 1, "uid": 0, "cid": "", "tcid": "", "pack": {"t": "dev", "cid": "", "bc": "4P12194037771__", "brand": "", "catalog": "", "mac": "24dfa70f1fa6", "mid": "11002", "model": "", "name": "a70f1fa6", "lock": 0, "series": "", "vender": "", "ver": ""}}
2020-11-28 00:35:16 DEBUG (MainThread) [greeclimate.network] Received response from device search
{'t': 'dev', 'cid': '', 'bc': '4P12194037771__', 'brand': '', 'catalog': '', 'mac': '24dfa70f1fa6', 'mid': '11002', 'model': '', 'name': 'a70f1fa6', 'lock': 0, 'series': '', 'vender': '', 'ver': ''}
```

**Comment by cmroche** [comment]
MID looks to be related, but not clear how. My MID is 10001, current firmware is v3.31

image

**Comment by xuefer** [comment]
pure guessing:
MID (in app and in protocol) sounds like Model ID of control board (instead of the whole device) while its version number (in global gree+) is hardware revision

see network log in this repo and https://github.com/tomikaa87/gree-remote/
with version lower than V4, it's a mess already. "model": "gree" is wrong in common sense

'bc' is bar code. reported as 'gree' incorrectly by <V4. but with =V4 all 'bc' (without ```__```) is identical to the bar code labeled on the device. bar code shown in app is encoded differently I suppose

```
{"t": "pack", "i": 1, "uid": 0, "cid": "", "tcid": "", "pack": {"t": "dev", "cid": "", "bc": "4P07680005173__", "brand": "", "catalog": "", "mac": "780f77a8ba4a", "mid": "11002", "model": "", "name": "77a8ba4a", "lock": 0, "series": "", "vender": "", "ver": ""}}
{"t": "pack", "i": 1, "uid": 0, "cid": "", "tcid": "", "pack": {"t": "dev", "cid": "", "bc": "4P11682034406__", "brand": "", "catalog": "", "mac": "780f77dd30f3", "mid": "11002", "model": "", "name": "77dd30f3", "lock": 0, "series": "", "vender": "", "ver": ""}}
{"t": "pack", "i": 1, "uid": 0, "cid": "", "tcid": "", "pack": {"t": "dev", "cid": "", "bc": "4P12194037771__", "brand": "", "catalog": "", "mac": "24dfa70f1fa6", "mid": "11002", "model": "", "name": "a70f1fa6", "lock": 0, "series": "", "vender": "", "ver": ""}}
{"t": "pack", "i": 1, "uid": 0, "cid": "", "tcid": "", "pack": {"t": "dev", "cid": "", "bc": "4P12194037775__", "brand": "", "catalog": "", "mac": "24dfa7102045", "mid": "11002", "model": "", "name": "a7102045", "lock": 0, "series": "", "vender": "", "ver": ""}}
```
sniffing app data using tcpdump is the only to go. let's the version isn't reported to cloud only

**Comment by cmroche** [comment]
I suspect that the information isn't communicated with the local protocol. It may not matter, as we can likely devise a test to check for support of the feature if required. Once I am done on the discovery refactor I'll test your changes on my model, which doesn't support TemSen, it should clarify how to proceed.

**Comment by xuefer** [comment]
It matter since the code need to decide if 40C or not for different firmware version, unless you have better idea like specified by user manually

**Comment by cmroche** [comment]
@xuefer As it turns out, I support this feature and wasn't even aware.

(venv) cliffordroche@Cliffords-iMac PythonCLI % python3 gree.py -c 192.168.1.29 -i f4911e7aca59 -k ... get TemSen
Getting parameter: TemSen
TemSen = 63

However I have the offset you do not. It's not clear to me yet that this is a function of the firmware version, though maybe you are right. It's conceivable it could be related to the region too?

It's like safe to assume that the operating range is [0,40]. The unit's themselves have a set range of [16,30] from what I can tell, so we could apply the offset based on the value reporting, at least until the difference becomes clearer.

**Comment by cmroche** [comment]
Another thought, maybe the temperature range related to the source of the temperature.

I'm using the IFeel functionality, is this something any of your devices support and could be checked?

**Comment by xuefer** [comment]
```if temperature > 40: temperature -= 40``` is a nice suggestion taking me into deep thinking

* Outdoor air temperature limit
Cooling mode: upper limit required to be 43C] by China standard, gree and most other vendor however up to 48C]
Heating mode: lower limit is [-15C

* Outdoor unit limit
auto stop at 70C

* real life temperature:
In door sensor report room temperature regardless of the AC operating limit
max temperature is under 40C in most area of China but with exceptions

let's say we pick signature to be 40C
automation will be confused if :
  1. room temperature >=41C for >=V4 users since 41-40=1C
  2. room temperature <=-1 for <V4 users since device report [-15,-1] as [25,39]

43C is safe for my automation living in south of China, but it's just me. ```if temperature > 43: temperature -= 40```

* more consideration
do 40 or 43C condition check, add a new entity telling raw sensor reading for automation

**Comment by xuefer** [comment]
or we can just assume version is 'V4' if version == '', simpler logic better result, yet much more coding 😄

**Comment by cmroche** [comment]
The versions in the discovery response don't correlate, and many devices don't even report it. However, what do you get with this

`python3 gree.py -c ... -i ... -k ... get hid`

I have

`hid = 362001000762+U-CS532AE(LT)V3.31.bin`

Do you have other < V4 devices to confirm your theory about TemSen being correlated for the version?

**Comment by xuefer** [comment]
> The versions in the discovery response don't correlate, and many devices don't even report it. However, what do you get with this
> 
> `python3 gree.py -c ... -i ... -k ... get hid`
> 
> I have
> 
> `hid = 362001000762+U-CS532AE(LT)V3.31.bin`
```
# ./get hid
gree.py -c 192.168.26.72 -i 77a8ba4a -k ... get hid
Getting parameter: hid
hid = 362001060297+U-CS532AF(MTK)V4.bin

gree.py -c 192.168.26.73 -i 77dd30f3 -k ... get hid
Getting parameter: hid
hid = 362001060297+U-CS532AF(MTK)V4.bin

gree.py -c 192.168.26.74 -i a70f1fa6 -k ... get hid
Getting parameter: hid
hid = 362001060297+U-CS532AF(MTK)V4.bin

gree.py -c 192.168.26.75 -i a7102045 -k ... get hid
Getting parameter: hid
hid = 362001060297+U-CS532AF(MTK)V4.bin
```
oldest manufacture date of the unit is 2018-08

> 
> Do you have other < V4 devices to confirm your theory about TemSen being correlated for the version?
nope, it was older firmware and upgraded twice, I don't remember the version before V4, but I wasn't playing with home assistant nor did I know TemSen before

**Comment by cmroche** [comment]
Ok, ok... I think this is something we can work with then.

**Comment by cmroche** [comment]
@xuefer I've brought your work to a new PR, #27 which should address what we've discovered. Tomorrow I'll add support to HA, and then test over a few days.

**Pull request closed without merging**
