### PR TITLE
Allow min temps down to 8C or 46F

### LINKED ISSUE #51: Adjust TEMP_MIN for models with 8C heating mode
Some of the latest Gree models such as Amber Nordic support heating temperatures down to 8C instead of having just one 8C heating mode.

Currently this library sets `TEMP_MIN` to 16C:

https://github.com/cmroche/greeclimate/blob/cd6a25f9556e6fd3d4871ac86883d114fc1e9b9e/greeclimate/device.py#L92

which prevents any temperatures below 16C to be sent to these devices:

https://github.com/cmroche/greeclimate/blob/cd6a25f9556e6fd3d4871ac86883d114fc1e9b9e/greeclimate/device.py#L342-L344

This appears to have been introduced with #31.

### PR DESCRIPTION
**Pull request by kasparsd**
Fixes #51.

Before #31 it was possible to set any temperature value so this reduces the limitations introduced in that changeset.

### CODE REVIEW

**Comment by cmroche** [comment]
@kasparsd Thanks for the contribution.

But, can you explain a bit how you are setting the 8C mode and the issue you are facing? On my unit, for instance, I cannot set the temperature lower than 16C with the remote or Gree+ app, the only way to get to 8C mode is to use the "Away" preset which disregards the temperature setting.

Assuming this is the way it ought to work, I'm not sure how this change addresses anything related to the 8C mode.

**Comment by cmroche** [comment]
Curiously, does it also have an 8C heat preset mode?

**Comment by kasparsd** [comment]
> Curiously, does it also have an 8C heat preset mode?

I tried pressing "TEMP" and "CLOCK" simultaneously on the remote but nothing happens -- there is also no beep from the indoor unit.

Same with the Home Assistant integration which uses `AWAY` for the 8C heating more -- setting that mode unsets itself just a few seconds later so I assume it gets a message back from the device that the mode didn't change.

**Comment by cmroche** [comment]
Also, I'm using conventional commit for the release system. Could you rebase your commit to: "fix: Allow min temps down to 8C or 46F"

**Comment by kasparsd** [comment]
Yeah, looks like the API is being changed and it is not very consistent between devices. Here is a screenshot from the `Func` tab on the app:

func

Notice how it doesn't have the 8C mode as a separate feature.

> Also, I'm using conventional commit for the release system. Could you rebase your commit to: "fix: Allow min temps down to 8C or 46F"

Yes, sure!

**Pull request merged**
